### ISSUE TITLE
Pulp interfering with main program logging system

### ISSUE THREAD

**Issue by ferranmc** [coin-or/pulp-or#75]
Hi,

   I'm using Pulp to generate some models from a main program. I'm using logging package and when I run pulp the logger configuration gets mixed up. I've check the code and the issue comes from pulp code calling directly to the root logger (logging.debug) instead of using a private logger. It seems you started to use the private logger, but there are still some calls to the root logger on file pulp.py (2) and solvers.py (1). If you could correct these calls pulp will be clean and not interfere with other package logger.

Thanks

**Comment by stumitchell** [comment]
Hopefully fixed
